{
  "name": "CI",
  "on": {
    "push": {
      "branches": [
        "master"
      ]
    },
    "pull_request": null,
    "schedule": [
      {
        "cron": "0 10 * * 1"
      }
    ]
  },
  "jobs": {
    "linter": {
      "runs-on": "ubuntu-latest",
      "env": {
        "OS": "ubuntu-latest",
        "QUICKLISP_DIST": "quicklisp",
        "LISP": "sbcl-bin"
      },
      "steps": [
        {
          "name": "Checkout Code",
          "uses": "actions/checkout@v4"
        },
        {
          "name": "Setup Common Lisp Environment",
          "uses": "40ants/setup-lisp@v4",
          "with": {
            "asdf-system": "40ants-asdf-system",
            "cache": "true"
          }
        },
        {
          "name": "Change dist to Ultralisp if qlfile does not exist",
          "run": "if [[ ! -e qlfile ]]; then echo 'dist ultralisp http://dist.ultralisp.org' > qlfile; fi",
          "shell": "bash"
        },
        {
          "name": "Update Qlot",
          "run": "qlot update --no-deps",
          "shell": "bash"
        },
        {
          "name": "Install SBLint wrapper",
          "run": "qlot exec ros install 40ants-asdf-system 40ants-linter",
          "shell": "bash"
        },
        {
          "name": "Run Linter",
          "run": "qlot exec 40ants-linter --system \"40ants-asdf-system, 40ants-asdf-system-docs, 40ants-asdf-system-tests\" --imports",
          "shell": "bash"
        }
      ]
    },
    "run-tests": {
      "strategy": {
        "fail-fast": false,
        "matrix": {
          "os": [
            "ubuntu-latest",
            "macos-latest"
          ],
          "exclude": [
            {
              "os": "ubuntu-latest",
              "quicklisp": "ultralisp",
              "lisp": "npt"
            },
            {
              "os": "ubuntu-latest",
              "quicklisp": "quicklisp",
              "lisp": "npt"
            },
            {
              "lisp": "allegro"
            },
            {
              "lisp": "clasp"
            },
            {
              "lisp": "mkcl"
            },
            {
              "os": "ubuntu-latest",
              "quicklisp": "quicklisp",
              "lisp": "ccl-bin"
            },
            {
              "os": "macos-latest",
              "quicklisp": "quicklisp",
              "lisp": "ccl-bin"
            },
            {
              "os": "macos-latest",
              "quicklisp": "ultralisp",
              "lisp": "ccl-bin"
            },
            {
              "os": "ubuntu-latest",
              "quicklisp": "quicklisp",
              "lisp": "abcl-bin"
            },
            {
              "os": "macos-latest",
              "quicklisp": "quicklisp",
              "lisp": "abcl-bin"
            },
            {
              "os": "macos-latest",
              "quicklisp": "ultralisp",
              "lisp": "abcl-bin"
            },
            {
              "os": "ubuntu-latest",
              "quicklisp": "quicklisp",
              "lisp": "allegro"
            },
            {
              "os": "macos-latest",
              "quicklisp": "quicklisp",
              "lisp": "allegro"
            },
            {
              "os": "macos-latest",
              "quicklisp": "ultralisp",
              "lisp": "allegro"
            },
            {
              "os": "ubuntu-latest",
              "quicklisp": "quicklisp",
              "lisp": "clasp"
            },
            {
              "os": "macos-latest",
              "quicklisp": "quicklisp",
              "lisp": "clasp"
            },
            {
              "os": "macos-latest",
              "quicklisp": "ultralisp",
              "lisp": "clasp"
            },
            {
              "os": "ubuntu-latest",
              "quicklisp": "quicklisp",
              "lisp": "lispworks"
            },
            {
              "os": "macos-latest",
              "quicklisp": "quicklisp",
              "lisp": "lispworks"
            },
            {
              "os": "macos-latest",
              "quicklisp": "ultralisp",
              "lisp": "lispworks"
            },
            {
              "os": "ubuntu-latest",
              "quicklisp": "quicklisp",
              "lisp": "mkcl"
            },
            {
              "os": "macos-latest",
              "quicklisp": "quicklisp",
              "lisp": "mkcl"
            },
            {
              "os": "macos-latest",
              "quicklisp": "ultralisp",
              "lisp": "mkcl"
            },
            {
              "os": "ubuntu-latest",
              "quicklisp": "quicklisp",
              "lisp": "ecl"
            },
            {
              "os": "macos-latest",
              "quicklisp": "quicklisp",
              "lisp": "ecl"
            },
            {
              "os": "macos-latest",
              "quicklisp": "ultralisp",
              "lisp": "ecl"
            }
          ],
          "quicklisp": [
            "ultralisp",
            "quicklisp"
          ],
          "lisp": [
            "sbcl-bin",
            "ccl-bin",
            "abcl-bin",
            "allegro",
            "clasp",
            "lispworks",
            "mkcl",
            "npt",
            "ecl"
          ]
        }
      },
      "runs-on": "${{ matrix.os }}",
      "env": {
        "OS": "${{ matrix.os }}",
        "QUICKLISP_DIST": "${{ matrix.quicklisp }}",
        "LISP": "${{ matrix.lisp }}"
      },
      "steps": [
        {
          "name": "Checkout Code",
          "uses": "actions/checkout@v4"
        },
        {
          "name": "Setup Common Lisp Environment",
          "uses": "40ants/setup-lisp@v4",
          "with": {
            "asdf-system": "40ants-asdf-system",
            "cache": "true"
          }
        },
        {
          "name": "Run Tests",
          "uses": "40ants/run-tests@v2",
          "with": {
            "asdf-system": "40ants-asdf-system",
            "coveralls-token": "\n${{ matrix.lisp == 'sbcl-bin' &&\n    matrix.os == 'ubuntu-latest' &&\n    matrix.quicklisp == 'ultralisp' &&\n    secrets.github_token }}"
          }
        }
      ]
    }
  }
}